In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\30698\appdata\roaming\python\python311\site-packages (2.1.2)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\30698\appdata\roaming\python\python311\site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\30698\appdata\roaming\python\python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\30698\appdata\roaming\python\python311\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\30698\appdata\roaming\python\python311\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\30698\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.3.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
movie_dat = r"C:\Users\30698\OneDrive\Desktop\ml-1m\movies.dat"
movie_file = r"C:\Users\30698\OneDrive\Desktop\ml-1m\movies.csv"

rating_dat = r"C:\Users\30698\OneDrive\Desktop\ml-1m\ratings.dat"
rating_file = r"C:\Users\30698\OneDrive\Desktop\ml-1m\ratings.csv"

user_dat = r"C:\Users\30698\OneDrive\Desktop\ml-1m\users.dat"
user_file = r"C:\Users\30698\OneDrive\Desktop\ml-1m\users.csv"

In [3]:
import csv

def convert_dat_to_csv(dat_file_path, csv_file_path):
    try:
        with open(dat_file_path, 'r') as dat_file:
            lines = dat_file.readlines()  # Read all lines from the .dat file

        with open(csv_file_path, 'w', newline='') as csv_file:
            writer = csv.writer(csv_file)
            for line in lines:
                # Split the line using '::' as the delimiter
                writer.writerow(line.strip().split('::'))
        
        print(f"File converted successfully: {csv_file_path}")
    except FileNotFoundError:
        print("The specified file was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [4]:
convert_dat_to_csv(movie_dat, movie_file)
convert_dat_to_csv(rating_dat, rating_file)
convert_dat_to_csv(user_dat, user_file)

File converted successfully: C:\Users\30698\OneDrive\Desktop\ml-1m\movies.csv
File converted successfully: C:\Users\30698\OneDrive\Desktop\ml-1m\ratings.csv
File converted successfully: C:\Users\30698\OneDrive\Desktop\ml-1m\users.csv

In [5]:
import pandas as pd

# Read the file with column names
movie_df = pd.read_csv(movie_file, encoding='ISO-8859-1', names=['Movie ID', 'Title', 'Genre'], header=None)

# Reset index to start from 1
movie_df.index = range(1, len(movie_df) + 1)

movie_df

,Movie ID,Title,Genre
1,1,Toy Story (1995),Animation|Children's|Comedy
2,2,Jumanji (1995),Adventure|Children's|Fantasy
3,3,Grumpier Old Men (1995),Comedy|Romance
4,4,Waiting to Exhale (1995),Comedy|Drama
5,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3879,3948,Meet the Parents (2000),Comedy
3880,3949,Requiem for a Dream (2000),Drama
3881,3950,Tigerland (2000),Drama
3882,3951,Two Family House (2000),Drama
3883,3952,"Contender, The (2000)",Drama|Thriller

In [6]:
# Extract everything within brackets
bracketed_items = movie_df['Title'].str.extractall(r'\((.*?)\)')

# Count the total number of bracketed items
total_count = len(bracketed_items)

# Display the total count
print(f"Total number of bracketed items: {total_count}")

Total number of bracketed items: 4153

In [7]:
# Extract the year from the title using a regular expression
movie_df['Year'] = movie_df['Title'].str.extract(r'\((\d{4})\)', expand=False)

# Remove the year from the Title column
movie_df['Title'] = movie_df['Title'].str.replace(r'\s*\(\d{4}\)', '', regex=True)

movie_df

,Movie ID,Title,Genre,Year
1,1,Toy Story,Animation|Children's|Comedy,1995
2,2,Jumanji,Adventure|Children's|Fantasy,1995
3,3,Grumpier Old Men,Comedy|Romance,1995
4,4,Waiting to Exhale,Comedy|Drama,1995
5,5,Father of the Bride Part II,Comedy,1995
...,...,...,...,...
3879,3948,Meet the Parents,Comedy,2000
3880,3949,Requiem for a Dream,Drama,2000
3881,3950,Tigerland,Drama,2000
3882,3951,Two Family House,Drama,2000
3883,3952,"Contender, The",Drama|Thriller,2000

In [8]:
movie_df.duplicated(subset=['Title', 'Year']).any()

False

In [9]:
movie_df.isna().any()

Movie ID    False
Title       False
Genre       False
Year        False
dtype: bool

In [10]:
# Extract everything within brackets
bracketed_items = movie_df['Title'].str.extractall(r'\((.*?)\)')

# Count the total number of bracketed items
total_count = len(bracketed_items)

# Display the total count
print(f"Total number of bracketed items: {total_count}")

movie_df['Title'] = movie_df['Title'].str.replace(r'\((.*?)\)', '', regex=True)

Total number of bracketed items: 270

In [11]:
# Read the file with column names
rating_df = pd.read_csv(rating_file, encoding='ISO-8859-1', names=['User ID', 'Movie ID', 'Rating', 'Timestamp'], header=None)

# Reset index to start from 1
rating_df.index = range(1, len(rating_df) + 1)

rating_df

         User ID  Movie ID  Rating  Timestamp
1              1      1193       5  978300760
2              1       661       3  978302109
3              1       914       3  978301968
4              1      3408       4  978300275
5              1      2355       5  978824291
...          ...       ...     ...        ...
1000205     6040      1091       1  956716541
1000206     6040      1094       5  956704887
1000207     6040       562       5  956704746
1000208     6040      1096       4  956715648
1000209     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [31]:
rating_df.duplicated(subset=['User ID', 'Movie ID']).any()

False

In [12]:
rating_df.isna().any()

User ID      False
Movie ID     False
Rating       False
Timestamp    False
dtype: bool

In [13]:
rating_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\ratings.csv", header=None)

In [14]:
data = rating_df['Timestamp']
date_df = pd.DataFrame(data)

# Convert 'Timestamp' column to a full date
date_df['Full Date'] = pd.to_datetime(date_df['Timestamp'], unit='s')

date_df['Year'] = date_df['Full Date'].dt.year
date_df['Month'] = date_df['Full Date'].dt.month
date_df['Day'] = date_df['Full Date'].dt.day
date_df['Hour'] = date_df['Full Date'].dt.hour
date_df['Minute'] = date_df['Full Date'].dt.minute
date_df['Second'] = date_df['Full Date'].dt.second

date_df = date_df.drop(columns=['Timestamp'])
date_df

                  Full Date  Year  Month  Day  Hour  Minute  Second
1       2000-12-31 22:12:40  2000     12   31    22      12      40
2       2000-12-31 22:35:09  2000     12   31    22      35       9
3       2000-12-31 22:32:48  2000     12   31    22      32      48
4       2000-12-31 22:04:35  2000     12   31    22       4      35
5       2001-01-06 23:38:11  2001      1    6    23      38      11
...                     ...   ...    ...  ...   ...     ...     ...
1000205 2000-04-26 02:35:41  2000      4   26     2      35      41
1000206 2000-04-25 23:21:27  2000      4   25    23      21      27
1000207 2000-04-25 23:19:06  2000      4   25    23      19       6
1000208 2000-04-26 02:20:48  2000      4   26     2      20      48
1000209 2000-04-26 02:19:29  2000      4   26     2      19      29

[1000209 rows x 7 columns]

In [15]:
date_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\rating_date.csv", header=None)

In [16]:
import pandas as pd

# Read the file with column names
user_df = pd.read_csv(user_file, encoding='ISO-8859-1', names=['User ID', 'Gender', 'Age', 'Occupation', 'Zip-Code'], header=None)

# Change 'M' to 1 and 'F' to 2, and ensure the values are integers
user_df['Gender'] = user_df['Gender'].map({'M': 1, 'F': 2}).astype(int)

# Reset index to start from 1
user_df.index = range(1, len(user_df) + 1)

user_df['Zip-Code'] = user_df['Zip-Code'].str.split('-').str[0]

user_df

      User ID  Gender  Age  Occupation Zip-Code
1           1       2    1          10    48067
2           2       1   56          16    70072
3           3       1   25          15    55117
4           4       1   45           7    02460
5           5       1   25          20    55455
...       ...     ...  ...         ...      ...
6036     6036       2   25          15    32603
6037     6037       2   45           1    76006
6038     6038       2   56           1    14706
6039     6039       2   45           0    01060
6040     6040       1   25           6    11106

[6040 rows x 5 columns]

In [17]:
user_df.isna().any()

User ID       False
Gender        False
Age           False
Occupation    False
Zip-Code      False
dtype: bool

In [30]:
user_df.duplicated(subset=['User ID']).any()

False

In [19]:
user_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\users.csv",header=None, index=False)

In [20]:
genre_mapping = {
    1: 'Action',
    2: 'Adventure',
    3: 'Animation',
    4: "Children's",
    5: 'Comedy',
    6: 'Crime',
    7: 'Documentary',
    8: 'Drama',
    9: 'Fantasy',
    10: 'Film-Noir',
    11: 'Horror',
    12: 'Musical',
    13: 'Mystery',
    14: 'Romance',
    15: 'Sci-Fi',
    16: 'Thriller',
    17: 'War',
    18: 'Western'
}

# Step 2: Create a DataFrame from the mapping
genre_df = pd.DataFrame(list(genre_mapping.items()), columns=['Genre ID', 'Genre'])

# Step 3: Save the DataFrame to a CSV file
genre_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\movie_genre.csv", header=None, index=False)
genre_df

    Genre ID        Genre
0          1       Action
1          2    Adventure
2          3    Animation
3          4   Children's
4          5       Comedy
5          6        Crime
6          7  Documentary
7          8        Drama
8          9      Fantasy
9         10    Film-Noir
10        11       Horror
11        12      Musical
12        13      Mystery
13        14      Romance
14        15       Sci-Fi
15        16     Thriller
16        17          War
17        18      Western

In [21]:
occupation_mapping = {
    0: "other/not specified",
    1: "academic/educator",
    2: "artist",
    3: "clerical/admin",
    4: "college/grad student",
    5: "customer service",
    6: "doctor/health care",
    7: "executive/managerial",
    8: "farmer",
    9: "homemaker",
    10: "K-12 student",
    11: "lawyer",
    12: "programmer",
    13: "retired",
    14: "sales/marketing",
    15: "scientist",
    16: "self-employed",
    17: "technician/engineer",
    18: "tradesman/craftsman",
    19: "unemployed",
    20: "writer"
}

occup_df = pd.DataFrame(list(occupation_mapping.items()), columns=['Occupation ID', 'Occupation'])

occup_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\user_occupation.csv", header=None, index=False)
occup_df

    Occupation ID            Occupation
0               0   other/not specified
1               1     academic/educator
2               2                artist
3               3        clerical/admin
4               4  college/grad student
5               5      customer service
6               6    doctor/health care
7               7  executive/managerial
8               8                farmer
9               9             homemaker
10             10          K-12 student
11             11                lawyer
12             12            programmer
13             13               retired
14             14       sales/marketing
15             15             scientist
16             16         self-employed
17             17   technician/engineer
18             18   tradesman/craftsman
19             19            unemployed
20             20                writer

In [22]:
age_mapping = {
    1: "Under 18",
    18: "18-24",
    25: "25-34",
    35: "35-44",
    45: "45-49",
    50: "50-55",
    56: "56+"
}

age_df = pd.DataFrame(list(age_mapping.items()), columns=['Age ID', 'Age Range'])

age_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\user_age.csv",header=None, index=False)

age_df

   Age ID Age Range
0       1  Under 18
1      18     18-24
2      25     25-34
3      35     35-44
4      45     45-49
5      50     50-55
6      56       56+

In [23]:
gender_mapping = {
    1: "male",
    2: "female"
}

gender_df = pd.DataFrame(list(gender_mapping.items()), columns=['Gender ID', 'Gender'])

gender_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\user_gender.csv", header=None, index=False)

gender_df

   Gender ID  Gender
0          1    male
1          2  female

In [24]:
movie_df['Genre'] = movie_df['Genre'].str.split('|')
df_exploded = movie_df.explode('Genre')

assosiate_df = df_exploded.merge(genre_df, on='Genre', how='left')
assosiate_df['Assosiation ID'] = assosiate_df.index + 1 

assosiate_df_f = assosiate_df[['Assosiation ID', 'Movie ID', 'Genre ID']]

assosiate_df_f.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\assosiations.csv", header=None, index=False)

assosiate_df_f

      Assosiation ID  Movie ID  Genre ID
0                  1         1         3
1                  2         1         4
2                  3         1         5
3                  4         2         2
4                  5         2         4
...              ...       ...       ...
6403            6404      3949         8
6404            6405      3950         8
6405            6406      3951         8
6406            6407      3952         8
6407            6408      3952        16

[6408 rows x 3 columns]

In [25]:
movie_df = movie_df.drop(columns=['Genre'])

movie_df

      Movie ID                        Title  Year
1            1                    Toy Story  1995
2            2                      Jumanji  1995
3            3             Grumpier Old Men  1995
4            4            Waiting to Exhale  1995
5            5  Father of the Bride Part II  1995
...        ...                          ...   ...
3879      3948             Meet the Parents  2000
3880      3949          Requiem for a Dream  2000
3881      3950                    Tigerland  2000
3882      3951             Two Family House  2000
3883      3952               Contender, The  2000

[3883 rows x 3 columns]

In [26]:
movie_df.to_csv(r"C:\Users\30698\OneDrive\Desktop\ml-1m\movies.csv", sep='#', header=None, index=False)